/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import ProjectDatabaseConnection.ConnectionProvider;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author shaun
 */
public class ViewExpenseSummary extends javax.swing.JFrame {

    /**
     * Creates new form vuewSummaryByCategory
     */
    
    String signInEmail="";
    
    static int categoryList2Count = 0;
    
    public ViewExpenseSummary(String sign_in_email) {
        initComponents();
        
        signInEmail = sign_in_email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        allSummaryButton = new rojerusan.RSMaterialButtonCircle();
        summaryCategoryTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        categoryList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        categoryList2 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryTable = new rojerusan.RSTableMetro();
        printSummaryTableButton = new rojerusan.RSMaterialButtonCircle();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        backPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1360, 750));
        setMinimumSize(new java.awt.Dimension(1360, 750));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backPanel.setBackground(new java.awt.Color(255, 51, 51));
        backPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backPanelMouseClicked(evt);
            }
        });
        backPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" Back");
        backPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jPanel1.add(backPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        allSummaryButton.setBackground(new java.awt.Color(255, 0, 0));
        allSummaryButton.setText("FETCH DETAILS");
        allSummaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSummaryButtonActionPerformed(evt);
            }
        });
        jPanel1.add(allSummaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 250, 60));

        summaryCategoryTextField.setBackground(new java.awt.Color(0, 51, 51));
        summaryCategoryTextField.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        summaryCategoryTextField.setForeground(new java.awt.Color(255, 255, 255));
        summaryCategoryTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        summaryCategoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryCategoryTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(summaryCategoryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 350, 30));

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Select any Expense Category");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 290, 30));

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/salary_category.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        categoryList1.setBackground(new java.awt.Color(0, 51, 51));
        categoryList1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        categoryList1.setForeground(new java.awt.Color(255, 255, 255));
        categoryList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Automobile", "Entertainment", "Health Care", "Household", "Personal", "Taxes", "Travel", "Other" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        categoryList1.setToolTipText("");
        categoryList1.setAutoscrolls(false);
        categoryList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        categoryList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                categoryList1ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(categoryList1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 150, 180));

        categoryList2.setBackground(new java.awt.Color(0, 51, 51));
        categoryList2.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        categoryList2.setForeground(new java.awt.Color(255, 255, 255));
        categoryList2.setToolTipText("");
        categoryList2.setAutoscrolls(false);
        categoryList2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        categoryList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                categoryList2ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(categoryList2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 230, 180));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Expense Summary");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 350, -1));

        jPanel9.setBackground(new java.awt.Color(0, 153, 0));
        jPanel9.setForeground(new java.awt.Color(255, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 390, 6));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 100));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 10, 760));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        summaryTable.setForeground(new java.awt.Color(102, 102, 255));
        summaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Income ID", "Date", "Amount", "Payer", "Mode Of Transaction", "Category"
            }
        ));
        summaryTable.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        summaryTable.setColorBordeFilas(new java.awt.Color(0, 51, 51));
        summaryTable.setColorBordeHead(new java.awt.Color(255, 255, 255));
        summaryTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        summaryTable.setEditingColumn(0);
        summaryTable.setEditingRow(0);
        summaryTable.setMultipleSeleccion(false);
        summaryTable.setRowHeight(35);
        jScrollPane1.setViewportView(summaryTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 770, 420));

        printSummaryTableButton.setBackground(new java.awt.Color(255, 0, 0));
        printSummaryTableButton.setText("PRINT");
        printSummaryTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printSummaryTableButtonActionPerformed(evt);
            }
        });
        jPanel2.add(printSummaryTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 230, 60));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 199));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 740, 840, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 199));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 840, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 100));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, -10, 10, 760));

        backPanel1.setBackground(new java.awt.Color(255, 51, 51));
        backPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backPanel1MouseClicked(evt);
            }
        });
        backPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("X");
        backPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jPanel2.add(backPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 50, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 780, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backPanelMouseClicked
        // TODO add your handling code here:5

        dispose();
        setVisible(false);
        new Home(signInEmail).setVisible(true);
    }//GEN-LAST:event_backPanelMouseClicked

    private void allSummaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSummaryButtonActionPerformed
        // TODO add your handling code here:

        String transactionCategory = summaryCategoryTextField.getText();
        
        if(transactionCategory.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please fill all the details");
            return;
        }
        
        // QUERY
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs;

            rs = st.executeQuery("select income_expense_id as 'Expense ID', transaction_date as Date, transaction_amount as Amount, transaction_category as Category, transaction_beneficiary as Beneficiary from Transaction where user_email='"+signInEmail+"' and transaction_category = '"+transactionCategory+"'");
            summaryTable.setModel(DbUtils.resultSetToTableModel(rs));
            

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_allSummaryButtonActionPerformed

    private void summaryCategoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryCategoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_summaryCategoryTextFieldActionPerformed

    private void categoryList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_categoryList1ValueChanged
        // TODO add your handling code here:

        // set to text field
        summaryCategoryTextField.setText(categoryList1.getSelectedValue());

        //Counter reset for 2nd category list
        categoryList2Count = 0;

        DefaultListModel listModel1 = new DefaultListModel();

        // AUTOMOBILE
        if((categoryList1.getSelectedValue()).equals("Automobile"))
        {
                String[] items = {"Fuel","Insurance","Loan","Maintainance","Other"};
                for(int i=0; i<items.length; i++)
                listModel1.addElement(items[i]);
                categoryList2.setModel(listModel1);
            }

        // ENTERTAINMENT
        else if((categoryList1.getSelectedValue()).equals("Entertainment"))
        {
                String[] items = {"Concerts","Movies", "OTT Platform", "Video Games/Consoles", "Other"};
                for(int i=0; i<items.length; i++)
                listModel1.addElement(items[i]);
                categoryList2.setModel(listModel1);
            }

        // HEALTH CARE
        else if((categoryList1.getSelectedValue()).equals("Health Care"))
        {
                String[] items = {"Medical Bills", "Loan", "Health Insurance", "Other"};
                for(int i=0; i<items.length; i++)
                listModel1.addElement(items[i]);
                categoryList2.setModel(listModel1);
            }

        // HOUSEHOLD
        else if((categoryList1.getSelectedValue()).equals("Household"))
        {
                String[] items = {"Groceries","Consumables", "Applicances", "Household Tools", "Loan", "Other"};
                for(int i=0; i<items.length; i++)
                listModel1.addElement(items[i]);
                categoryList2.setModel(listModel1);
            }

        // PERSONAL
        else if((categoryList1.getSelectedValue()).equals("Personal"))
        {
                String[] items = {"Clothing" ,"Grooming", "Child Care", "Education", "Other"};
                for(int i=0; i<items.length; i++)
                listModel1.addElement(items[i]);
                categoryList2.setModel(listModel1);
            }

        // TAXES
        else if((categoryList1.getSelectedValue()).equals("Taxes"))
        {
                String[] items = {"Service Tax" ,"Property Tax", "Sales Tax", "Income Tax", "Other"};
                for(int i=0; i<items.length; i++)
                listModel1.addElement(items[i]);
                categoryList2.setModel(listModel1);
            }

        // TRAVEL
        else if((categoryList1.getSelectedValue()).equals("Travel"))
        {
                String[] items = {"Travel Tickets" ,"Hotel Bills", "Other"};
                for(int i=0; i<items.length; i++)
                listModel1.addElement(items[i]);
                categoryList2.setModel(listModel1);
            }

        else
        {
                listModel1.addElement("");
                categoryList2.setModel(listModel1);
        }
    }//GEN-LAST:event_categoryList1ValueChanged

    private void categoryList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_categoryList2ValueChanged
        // TODO add your handling code here:

        //**** TO RESET THE VALUE OF CATEGORY while retaining the value from 1st category
        String str="";
        String str2="";

        if(categoryList2Count == 1)
        {
                str = summaryCategoryTextField.getText();
                char[] ch1 = new char[str.length()];

                for(int i=0; i<str.length() ; i++)
                {
                        ch1[i] = str.charAt(i);
                        if(ch1[i] == ' ')
                        break;
                        str2 = str2+ch1[i];
                    }

                System.out.println(str2);

                summaryCategoryTextField.setText(str2 + " - " + categoryList2.getSelectedValue());

                return;
            }
        String expenseCategory = categoryList2.getSelectedValue();
        summaryCategoryTextField.setText(summaryCategoryTextField.getText() + " - " + expenseCategory);

        categoryList2Count = 1;
    }//GEN-LAST:event_categoryList2ValueChanged

    private void printSummaryTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printSummaryTableButtonActionPerformed
        // TODO add your handling code here:

        try
        {
            summaryTable.print(JTable.PrintMode.FIT_WIDTH);
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_printSummaryTableButtonActionPerformed

    private void backPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backPanel1MouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(new ExpenseManager(),"Sure? You want to exit?", "Expense Manager", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if(result == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_backPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewExpenseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewExpenseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewExpenseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewExpenseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewExpenseSummary("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle allSummaryButton;
    private javax.swing.JPanel backPanel;
    private javax.swing.JPanel backPanel1;
    private javax.swing.JList<String> categoryList1;
    private javax.swing.JList<String> categoryList2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private rojerusan.RSMaterialButtonCircle printSummaryTableButton;
    private javax.swing.JTextField summaryCategoryTextField;
    private rojerusan.RSTableMetro summaryTable;
    // End of variables declaration//GEN-END:variables
}
